# Generated by Django 4.1.4 on 2023-01-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
